spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: REGION
    password: REGION
    initialization-mode: always
    driver-class-name: oracle.jdbc.OracleDriver
  jpa: 
    database: oracle
    hibernate: 
      ddl-auto: update
server:
  port: 8081
