INSERT INTO TODO_STATUS_INFO(STATUS_ID, STATUS_NAME) VALUES (1, '日次');
INSERT INTO TODO_STATUS_INFO(STATUS_ID, STATUS_NAME) VALUES (2, '週次');
INSERT INTO TODO_STATUS_INFO(STATUS_ID, STATUS_NAME) VALUES(3, '月次');
INSERT INTO TODO_STATUS_INFO(STATUS_ID, STATUS_NAME) VALUES(4, '１回のみ');
